# Site settings
title: HCMGIS Profile
description: >- # this means to ignore newlines until "baseurl:"
  HCMGIS Profile.
#baseurl: "/profile"  # the subpath of your site, e.g. /blog
url: "https://hcmgis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: hcmgis/hcmgis.github.io


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : HCMGIS
  image    : https://hcmgis.vn/wp-content/uploads/2017/12/screencapture-maps-hcmgis-vn-maps-1514888464395-e1534821791263-1200x384.png
  email    : hcmgis.dost@gmail.com
  github   : hcmgis
  twitter  : hcmgis
  linkedin : hcmgis
  facebook : hcmgis


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
